name: talkingquickly
description: 'rails, docker, stress free deployment and small steps taken quickly'
meta_description: "Blog by Ben Dixon, Ruby on Rails Developer, about rails, devops, docker, climbing and startups"

permalink: /:year/:month/:title

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
excerpt_separator: <!--more-->

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

feed:
  path: rss.xml

# Details for the RSS feed generator
url:            'https://www.talkingquickly.co.uk'
author:         'Ben Dixon'

collections:
  travel:
    output: true
    permalink: /travel/:path/
